<a href="https://colab.research.google.com/github/ProtegeAA/tensor/blob/main/tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [3]:
my_list = [[1,2,3,4,5], [6,7,8,9,10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

In [4]:
np1 = np.random.rand(3,4)
np1

array([[0.09044512, 0.32494299, 0.07002109, 0.70885428],
       [0.0028617 , 0.95708938, 0.63665923, 0.92236742],
       [0.94138628, 0.14377963, 0.94286633, 0.20532971]])

In [5]:
np1.dtype

dtype('float64')

In [6]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[ 0.7365, -0.2625, -0.1717, -0.4161],
        [-0.0950,  0.6664, -1.3267, -1.5095],
        [ 0.2327,  0.0906, -0.6059, -0.8905]])

In [7]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [9]:
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.0904, 0.3249, 0.0700, 0.7089],
        [0.0029, 0.9571, 0.6367, 0.9224],
        [0.9414, 0.1438, 0.9429, 0.2053]], dtype=torch.float64)