<a href="https://colab.research.google.com/github/ProtegeAA/tensor/blob/main/tensor_math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [2]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [3]:
# Shorthand addition
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [5]:
# Longhand addition - same as above but written so:
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [6]:
# Subtraction
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [7]:
# Sub function
torch.sub(tensor_b, tensor_a)

tensor([4, 4, 4, 4])

In [8]:
# Multiplication
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [9]:
# Mult longhand
torch.mul(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

In [10]:
# Division - converted to float due to remainders being common
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [11]:
# Division long hand
torch.div(tensor_b, tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [12]:
# Remainder Modulus
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [13]:
# Remainder Longhand
torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

In [14]:
# Exponents
torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])

In [15]:
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

In [16]:
# Reassignment
tensor_a.add_(tensor_b)

tensor([ 6,  8, 10, 12])

In [17]:
tensor_a

tensor([ 6,  8, 10, 12])